name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - gym-box2d=0.17
  - gym-classic_control=0.17
  - joblib=0.15
  - jupyterlab=1.2
  - nodejs=13
  - pip=20.0
  - pip:
    - -e git+https://github.com/udacity/deep-reinforcement-learning.git#egg=unityagents&subdirectory=python
    - -r file:requirements.txt
  - python=3.6
  - pytorch=0.4
  - cuda90
